/*Copyright (c) 2015-2016 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.test_mobi_18thnov.testproc.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.*;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.test_mobi_18thnov.testproc.*;


/**
 * ServiceImpl object for domain model class Table4.
 * @see com.test_mobi_18thnov.testproc.Table4
 */
@Service("Testproc.Table4Service")
public class Table4ServiceImpl implements Table4Service {


    private static final Logger LOGGER = LoggerFactory.getLogger(Table4ServiceImpl.class);

    @Autowired
    @Qualifier("Testproc.Table4Dao")
    private WMGenericDao<Table4, Integer> wmGenericDao;
    public void setWMGenericDao(WMGenericDao<Table4, Integer> wmGenericDao){
        this.wmGenericDao = wmGenericDao;
    }
     @Transactional(readOnly = true, value = "TestprocTransactionManager")
     public Page<Table4> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable){
          LOGGER.debug("Fetching all associated");
          return this.wmGenericDao.getAssociatedObjects(value, entityName, key, pageable);
     }

    @Transactional(value = "TestprocTransactionManager")
    @Override
    public Table4 create(Table4 table4) {
        LOGGER.debug("Creating a new table4 with information: {}" , table4);
        return this.wmGenericDao.create(table4);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "TestprocTransactionManager")
    @Override
    public Table4 delete(Integer table4Id) throws EntityNotFoundException {
        LOGGER.debug("Deleting table4 with id: {}" , table4Id);
        Table4 deleted = this.wmGenericDao.findById(table4Id);
        if (deleted == null) {
            LOGGER.debug("No table4 found with id: {}" , table4Id);
            throw new EntityNotFoundException(String.valueOf(table4Id));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(readOnly = true, value = "TestprocTransactionManager")
    @Override
    public Page<Table4> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all table4s");
        return this.wmGenericDao.search(queryFilters, pageable);
    }
    
    @Transactional(readOnly = true, value = "TestprocTransactionManager")
    @Override
    public Page<Table4> findAll(Pageable pageable) {
        LOGGER.debug("Finding all table4s");
        return this.wmGenericDao.search(null, pageable);
    }

    @Transactional(readOnly = true, value = "TestprocTransactionManager")
    @Override
    public Table4 findById(Integer id) throws EntityNotFoundException {
        LOGGER.debug("Finding table4 by id: {}" , id);
        Table4 table4=this.wmGenericDao.findById(id);
        if(table4==null){
            LOGGER.debug("No table4 found with id: {}" , id);
            throw new EntityNotFoundException(String.valueOf(id));
        }
        return table4;
    }
    @Transactional(rollbackFor = EntityNotFoundException.class, value = "TestprocTransactionManager")
    @Override
    public Table4 update(Table4 updated) throws EntityNotFoundException {
        LOGGER.debug("Updating table4 with information: {}" , updated);
        this.wmGenericDao.update(updated);
        return this.wmGenericDao.findById((Integer)updated.getId());
    }

    @Transactional(readOnly = true, value = "TestprocTransactionManager")
    @Override
    public long countAll() {
        return this.wmGenericDao.count();
    }
}


